version: 0.2

phases:
  install:
    commands:
      - echo Installing Terraform 1.5.7...
      - curl -fsSL https://releases.hashicorp.com/terraform/1.5.7/terraform_1.5.7_linux_amd64.zip -o terraform.zip
      - unzip terraform.zip && mv terraform /usr/local/bin/ && terraform -version

      - echo Installing kubectl 1.28...
      - curl -LO https://dl.k8s.io/release/v1.28.0/bin/linux/amd64/kubectl
      - chmod +x kubectl && mv kubectl /usr/local/bin/ && kubectl version --client

      - echo Installing Helm...
      - curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

  pre_build:
    commands:
      - echo "Initializing Terraform"
      - terraform -chdir=terraform init

  build:
    commands:
      - echo "Applying Terraform"
      - terraform -chdir=terraform apply -auto-approve
      - echo "Updating kubeconfig"
      - aws eks --region $AWS_REGION update-kubeconfig --name my-eks-cluster
      - chmod +x ./scripts/deploy.sh
      - ./scripts/deploy.sh

