name: Terraform Plan

on:
  push:
    paths:
      - "terraform/**"
  pull_request:
    paths:
      - "terraform/**"

env:
  AWS_REGION: us-east-1

jobs:
  plan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            ${{ env.AWS_REGION }}

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Init
        working-directory: terraform
        run: terraform init

      - name: Fmt & Validate
        working-directory: terraform
        run: |
          terraform fmt -check
          terraform validate

      - name: Terraform Plan
        id: plan
        working-directory: terraform
        run: |
          terraform plan -out=tfplan
          terraform show -no-color tfplan > plan.txt

      - name: Upload plan artifact
        uses: actions/upload-artifact@v3
        with:
          name: tfplan
          path: terraform/tfplan

      - name: Add plan to job summary
        run: cat terraform/plan.txt >> $GITHUB_STEP_SUMMARY
